### ISSUE TITLE
[BUG] Error during the validation

### ISSUE THREAD

**Issue by atamazian** [tubo213/kaggle-child-mind-institute-detect-sleep-states#36]
I'm getting the following error:
```
Epoch 0: 100% 119/119 [02:51<00:00,  1.44s/it, v_num=0]
Validation: 0it [00:00, ?it/s]
Validation:   0% 0/151 [00:00<?, ?it/s]
Validation DataLoader 0:   0% 0/151 [00:00<?, ?it/s]
Validation DataLoader 0:  13% 20/151 [00:08<00:56,  2.32it/s]
Validation DataLoader 0:  26% 40/151 [00:14<00:39,  2.78it/s]
Validation DataLoader 0:  40% 60/151 [00:20<00:30,  2.98it/s]
Validation DataLoader 0:  53% 80/151 [00:25<00:22,  3.09it/s]
Validation DataLoader 0:  66% 100/151 [00:31<00:16,  3.15it/s]
Validation DataLoader 0:  79% 120/151 [00:37<00:09,  3.22it/s]
Validation DataLoader 0:  93% 140/151 [00:42<00:03,  3.27it/s]
Validation DataLoader 0: 100% 151/151 [00:46<00:00,  3.28it/s]Error executing job with overrides: []
Traceback (most recent call last):
  File "/content/kaggle-child-mind-institute-detect-sleep-states/run/train.py", line 73, in main
    trainer.fit(model, datamodule=datamodule)
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1023, in _run_stage
    self.fit_loop.run()
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 355, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 134, in run
    self.on_advance_end()
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 249, in on_advance_end
    self.val_loop.run()
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 122, in run
    return self.on_run_end()
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 244, in on_run_end
    self._on_evaluation_epoch_end()
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 326, in _on_evaluation_epoch_end
    call._call_lightning_module_hook(trainer, hook_name)
  File "/content/kaggle-child-mind-institute-detect-sleep-states/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 146, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/content/kaggle-child-mind-institute-detect-sleep-states/src/modelmodule.py", line 97, in on_validation_epoch_end
    preds=preds[:, :, [1, 2]],
IndexError: index 2 is out of bounds for axis 2 with size 2

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Epoch 0: 100% 119/119 [03:57<00:00,  2.00s/it, v_num=0]
```

**Comment by tubo213** [comment]
@atamazian 
The bug was created when the code was UPDATED.
Fixed.See PR below.

https://github.com/tubo213/kaggle-child-mind-institute-detect-sleep-states/pull/37

**Comment by tubo213** [comment]
https://github.com/tubo213/kaggle-child-mind-institute-detect-sleep-states/pull/37

**Comment by tubo213** [comment]
@atamazian 

Please comment on [Disscussion](https://www.kaggle.com/competitions/child-mind-institute-detect-sleep-states/discussion/452940#2530545) for a summary, as exchanges on github may fall under the category of private sharing.

**Comment by atamazian** [comment]
Done
